### ISSUE TITLE
Form transforms.json file with known camera calibrations

### ISSUE THREAD

**Issue by z78406** [Lewis-Stuart-11/3DGS-to-PC#4]
Hi, Nice work for the community! I am currently working on my customed dataset where I have got the camera intrinsic and extrinsic matrix through calibrations. Could you please give a hint on how to generate a transforms.json file given camera matrix already known? Any instruction or a template file of transforms.json would be appreciated. Thx!

**Comment by Lewis-Stuart-11** [comment]
Hi,

Thank you! So the format of where you include the camera intrinsic information depends on if you have multiple cameras for the different images. If not, you can put the intrinsic information outside of the 'frames' key in the file, otherwise you will need to include this information per frame. The intrinsic information should be included as follows:

_{
"k1": ,
"k2": ,
"k3": 0,
"k4": 0,
"p1": 0,
"p2": 0,
"is_fisheye": false,
"w": 0,
"h": 0,
"fl_x": 0
"fl_y": 0,
"cx": 0,
"cy": 0,
"camera_angle_x": 0,
"camera_angle_y": 0
}_

I've set the values to 0, but replace these with your own. These parameters are essentially the following:
- K and P are the distortion values (if you have these include them, if not then don't worry)
- W and H are the width and height
- fl_x and fl_y are the focal length of the camera in both dimensions 
- cx and cy is the principal point in both dimensions
- camera_angle_x and camera_angle_y are the FOV of the camera (required) 

For the extrinsic parameters, each image and its transformation matrix are included in the 'frames' part of the JSON file. The extrinsic information should be included as follows:

_"frames":[
{
"transform_matrix": [
                [
                    1.0,
                    0.0,
                    0.0,
                    0.0
                ],
                [
                    0.0,
                    1.0,
                    0.0,
                    0.0
                ],
                [
                    0.0,
                    0.0,
                    1.0,
                    0.0
                ],
                [
                    0.0,
                    0.0,
                    0.0,
                    1.0
                ]
            ],
"file_path": "",
 "sharpness": },
]}_

You create a new frame for every image and include this in the frames list. The file path and transformation matrix are required for each image. The 'sharpness' parameter is the 'image sharpness' and can be calculated using the following code:

sharpness = cv2.Laplacian(cv2.cvtColor(image, cv2.COLOR_BGR2GRAY), cv2.CV_64F).var()

This is not required though. If you have depth or mask images these can be included as 'depth_mask' and 'mask_path' parameters as well.

If you need more info, check out: https://docs.nerf.studio/quickstart/data_conventions.html

Hope this helps.
